apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-serve-final
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-serve-final
    spec:
      containers:
      - name: nginx
        image: pomtcom/nginx-serve9
        ports:
        - containerPort: 80
          protocol: TCP